import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // ═══════════════════════════════════════════════════════════════════════
    // GLOBAL / SHARED
    // ═══════════════════════════════════════════════════════════════════════
    search_placeholder: "Search patients, records, incidents...",
    logout: "Sign Out",
    notifications: "Notifications",
    mark_all_read: "Mark all read",
    no_notifications: "You're all caught up!",
    loading: "Loading...",
    no_data: "No data available.",
    error_occurred: "An error occurred.",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    dash_welcome: "Welcome back",
    dash_subtitle: "System overview, QA reviews, and clinical operations status.",

    // Menu Categories
    category_overview: "Overview",
    category_records: "Records",
    category_community_care: "Community Care",
    category_clinical_services: "Clinical Services",
    category_operations: "Operations",
    category_admin: "Admin",
    category_compliance: "Compliance",

    // Menu Items
    menu_dashboard: "Dashboard",
    menu_user_guide: "User Guide",
    menu_epcr: "EPCR Registry",
    menu_qa_forms: "QA Forms",
    menu_qa_reviews: "QA Reviews",
    menu_qa_rules: "QA Rules",
    menu_rules_engine: "Rules Engine",
    menu_form_templates: "Form Templates",
    menu_medications: "Medication Safety",
    menu_bed_management: "Bed Management",
    menu_patient_scheduling: "Patient Scheduling",
    menu_waitlist_management: "Waitlist Management",
    menu_tb_cases: "TB Case Management",
    menu_homecare_dispatch: "Home Care Dispatch",
    menu_my_hc_schedule: "My HC Schedule",
    menu_cfs: "Child & Family Services",
    menu_surgical: "Surgical Care",
    menu_ophthalmology: "Ophthalmology",
    menu_dental: "Dental Care",
    menu_ltc: "Long-Term Care",
    menu_mental_health: "Mental Health",
    menu_rehab: "Rehabilitation Services",
    menu_ambulatory: "Ambulatory Referrals",
    menu_workflows: "Workflows",
    menu_deployments: "Deployments",
    menu_reports: "Reports & Analytics",
    menu_feedback: "Feedback Threads",
    menu_medical_travel: "Medical Travel",
    menu_organizations: "Organizations",
    menu_users: "User Management",
    menu_tickets: "Support Tickets",
    menu_audit_logs: "Audit Logs",
    menu_settings: "System Settings",
    menu_claims: "Claims Management",
    menu_payouts: "Provider Payments",
    menu_labs: "Lab & Diagnostic Orders",
    menu_discharge: "Discharge Management",
    menu_non_med_orders: "Non-Medication Orders",
    menu_hipaa_consent: "HIPAA Consent",
    menu_hipaa_disclosure: "HIPAA Disclosure",
    menu_baa: "Business Associates",
    menu_deid: "De-Identification Engine",
    menu_patient_portal: "Patient Portal",
    menu_patient_history: "Patient History",
    menu_registration: "Healthcare Registration",
    menu_break_glass: "Break-Glass Emergency",
    menu_critical_followups: "Critical Follow-Ups",
    menu_retention: "Retention & Archiving",
    menu_ontario_integration: "Ontario Health Integrations",

    // Common Actions
    action_save: "Save",
    action_cancel: "Cancel",
    action_close: "Close",
    action_submit: "Submit",
    action_filter: "Filter",
    action_export: "Export",
    action_new: "New Record",
    action_search: "Search",
    action_create: "Create",
    action_edit: "Edit",
    action_delete: "Delete",
    action_view: "View",
    action_update: "Update",
    action_back: "Back",
    action_next: "Next",
    action_previous: "Previous",
    action_refresh: "Refresh",
    action_download: "Download",
    action_print: "Print",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // FRENCH (FR) TRANSLATIONS
  // ═══════════════════════════════════════════════════════════════════════
  fr: {
    search_placeholder: "Rechercher patients, dossiers, incidents...",
    logout: "Déconnexion",
    notifications: "Notifications",
    mark_all_read: "Tout marquer comme lu",
    no_notifications: "Vous êtes à jour !",
    loading: "Chargement...",
    no_data: "Aucune donnée disponible.",
    error_occurred: "Une erreur est survenue.",
    confirm: "Confirmer",
    yes: "Oui",
    no: "Non",

    // Menu Categories
    category_overview: "Aperçu",
    category_records: "Dossiers",
    category_community_care: "Soins communautaires",
    category_clinical_services: "Services cliniques",
    category_operations: "Opérations",
    category_admin: "Administration",
    category_compliance: "Conformité",

    // Menu Items
    menu_dashboard: "Tableau de bord",
    menu_user_guide: "Guide de l'utilisateur",
    menu_epcr: "Registre ePCR",
    menu_qa_forms: "Formulaires AQ",
    menu_qa_reviews: "Révisions AQ",
    menu_qa_rules: "Règles AQ",
    menu_rules_engine: "Moteur de règles",
    menu_form_templates: "Modèles de formulaires",
    menu_medications: "Sécurité des médicaments",
    menu_bed_management: "Gestion des lits",
    menu_patient_scheduling: "Planification des patients",
    menu_waitlist_management: "Liste d'attente",
    menu_tb_cases: "Gestion de la tuberculose",
    menu_homecare_dispatch: "Soins à domicile",
    menu_my_hc_schedule: "Mon horaire de soins",
    menu_cfs: "Services à l'enfance",
    menu_surgical: "Soins chirurgicaux",
    menu_ophthalmology: "Ophtalmologie",
    menu_dental: "Soins dentaires",
    menu_ltc: "Soins de longue durée",
    menu_mental_health: "Santé mentale",
    menu_rehab: "Services de réadaptation",
    menu_ambulatory: "Références ambulatoires",
    menu_workflows: "Flux de travail",
    menu_deployments: "Déploiements",
    menu_reports: "Rapports et analyses",
    menu_feedback: "Commentaires",
    menu_medical_travel: "Voyages médicaux",
    menu_organizations: "Organisations",
    menu_users: "Gestion des utilisateurs",
    menu_tickets: "Billets de support",
    menu_audit_logs: "Journaux d'audit",
    menu_settings: "Paramètres système",
    menu_claims: "Réclamations",
    menu_payouts: "Paiements prestataires",
    menu_labs: "Analyses & Laboratoire",
    menu_discharge: "Gestion des sorties",
    menu_non_med_orders: "Ordonnances non médicamenteuses",
    menu_hipaa_consent: "Consentement HIPAA",
    menu_hipaa_disclosure: "Divulgation HIPAA",
    menu_baa: "Associés commerciaux",
    menu_deid: "Désidentification",
    menu_patient_portal: "Portail du patient",
    menu_patient_history: "Historique patient",
    menu_registration: "Inscription santé",
    menu_break_glass: "Accès d'urgence",
    menu_critical_followups: "Suivis critiques",
    menu_retention: "Rétention et archivage",
    menu_ontario_integration: "Intégrations Ontario",

    // Common Actions
    action_save: "Enregistrer",
    action_cancel: "Annuler",
    action_close: "Fermer",
    action_submit: "Soumettre",
    action_filter: "Filtrer",
    action_export: "Exporter",
    action_new: "Nouveau dossier",
    action_search: "Rechercher",
    action_create: "Créer",
    action_edit: "Modifier",
    action_delete: "Supprimer",
    action_view: "Voir",
    action_update: "Mettre à jour",
    action_back: "Retour",
    action_next: "Suivant",
    action_previous: "Précédent",
    action_refresh: "Actualiser",
    action_download: "Télécharger",
    action_print: "Imprimer",
  }
};

// Comprehensive Auto-translation dictionary for English phrases to French
const frAutoDictionary = {
  // Global & General Actions
  "Search": "Rechercher",
  "Search...": "Rechercher...",
  "Search patient": "Rechercher un patient",
  "Search patient...": "Rechercher un patient...",
  "Search patients, records, incidents...": "Rechercher patients, dossiers, incidents...",
  "Search patient, location, ID…": "Rechercher patient, lieu, ID…",
  "Search resident ID or bed...": "Rechercher no de résident ou lit...",
  "Search child name, case #...": "Rechercher nom de l'enfant, no de dossier...",
  "Search patient, plan #...": "Rechercher patient, no de plan...",
  "Type patient name...": "Saisir le nom du patient...",
  "Active": "Actif",
  "Completed": "Terminé",
  "Pending": "En attente",
  "Draft": "Brouillon",
  "Approved": "Approuvé",
  "Rejected": "Rejeté",
  "Critical": "Critique",
  "High": "Élevé",
  "Moderate": "Modéré",
  "Low": "Faible",
  "Status": "Statut",
  "Action": "Action",
  "Actions": "Actions",
  "Date": "Date",
  "Time": "Heure",
  "Name": "Nom",
  "Patient": "Patient",
  "Patient Name": "Nom du patient",
  "Patient ID": "No du patient",
  "Provider": "Prestataire",
  "Facility": "Établissement",
  "Notes": "Notes",
  "Description": "Description",
  "Type": "Type",
  "Priority": "Priorité",
  "Save": "Enregistrer",
  "Cancel": "Annuler",
  "Close": "Fermer",
  "Submit": "Soumettre",
  "Filter": "Filtrer",
  "Export": "Exporter",
  "New": "Nouveau",
  "New Record": "Nouveau dossier",
  "Create": "Créer",
  "Edit": "Modifier",
  "Delete": "Supprimer",
  "View": "Voir",
  "Update": "Mettre à jour",
  "Back": "Retour",
  "Next": "Suivant",
  "Previous": "Précédent",
  "Refresh": "Actualiser",
  "Download": "Télécharger",
  "Print": "Imprimer",
  "All": "Tous",
  "General": "Général",
  "Emergency": "Urgence",
  "Total": "Total",
  "Details": "Détails",
  "Loading...": "Chargement...",
  "No data available.": "Aucune donnée disponible.",

  // Form Steps & Navigation
  "Subject": "Sujet / Patient",
  "Incident": "Incident",
  "Clinical": "Clinique",
  "Disposition": "Orientation / Transport",
  "New Patient": "Nouveau patient",
  "Existing Patient": "Patient existant",
  "Search by Phone Number": "Rechercher par téléphone",
  "Search Results": "Résultats de recherche",
  "CLINICAL WORKFLOW": "FLUX DE TRAVAIL CLINIQUE",
  "Clear AI Highlights": "Effacer surbrillance IA",
  "Save Record": "Enregistrer le dossier",
  "Update Record": "Mettre à jour le dossier",
  "Saving...": "Enregistrement...",
  "Next Step": "Étape suivante",
  "Previous Step": "Étape précédente",
  "First Name": "Prénom",
  "Last Name": "Nom de famille",
  "Phone Number": "Numéro de téléphone",
  "Emergency Contact": "Contact d'urgence",
  "Primary Care Physician": "Médecin traitant",
  "Insurance Policy #": "Nº de police d'assurance",
  "Health Card #": "Nº de carte d'assurance maladie",
  "Street Address": "Adresse postale",
  "Postal Code": "Code postal",
  "Incident Date & Time": "Date et heure de l'incident",
  "Incident Location": "Lieu de l'incident",
  "Response Unit / Vehicle": "Unité d'intervention / Véhicule",
  "Dispatcher Call #": "Nº d'appel de répartition",
  "Chief Complaint & History": "Motif de consultation et historique",
  "Narrative / Clinical Assessment": "Récit / Évaluation clinique",
  "Vital Signs": "Constantes vitales",
  "Medications Administered": "Médicaments administrés",
  "Procedures Performed": "Procédures réalisées",
  "Destination Facility": "Établissement de destination",
  "Transport Mode": "Mode de transport",
  "Patient Disposition": "Orientation du patient",

  // Dashboard KPI Cards & Labels
  "Total EPCR Records": "Dossiers ePCR totaux",
  "QA Reviews": "Révisions AQ",
  "Pending QA": "AQ en attente",
  "Unread Alerts": "Alertes non lues",
  "Pending Reviews": "Révisions en attente",
  "Total QA Reviews": "Total des révisions AQ",
  "Needs Attention": "Attention requise",
  "My Records": "Mes dossiers",
  "Drafts": "Brouillons",
  "Submitted": "Soumis",
  "Critical Follow-Ups": "Suivis critiques",
  "Recent EPCR Records": "Dossiers ePCR récents",
  "Quick Access": "Accès rapide",
  "QA Compliance Flux": "Évolution de la conformité AQ",
  "Incident Hotspots": "Points chauds d'incidents",
  "Good morning": "Bonjour",
  "Good afternoon": "Bon après-midi",
  "Good evening": "Bonsoir",

  // Clinical Domain KPIs & Tab Headers
  "Active Cases": "Cas actifs",
  "Crisis Alerts": "Alertes de crise",
  "Sessions Today": "Séances aujourd'hui",
  "Recovery Plans": "Plans de rétablissement",
  "Active CFS Cases": "Cas SEF actifs",
  "High/Immediate Risk": "Risque élevé/immédiat",
  "Foster Placements": "Placements en foyer d'accueil",
  "Custom Adoptions": "Adoptions coutumières",
  "Active Rehab Plans": "Plans de réadaptation actifs",
  "PT / OT Caseload": "Charge PT / OT",
  "Latest FIM Score": "Dernier score FIM",
  "Child Dev Assessments": "Évaluations développement de l'enfant",
  "Total Admitted Residents": "Résidents admis totaux",
  "Long-Stay Residents": "Résidents longue durée",
  "Restorative Care": "Soins de restauration",
  "LTC Facilities": "Établissements SLD",

  // Category & Navigation Headings
  "Dashboard": "Tableau de bord",
  "Records": "Dossiers",
  "Overview": "Aperçu",
  "Clinical Services": "Services cliniques",
  "Community Care": "Soins communautaires",
  "Operations": "Opérations",
  "Admin": "Administration",
  "Compliance": "Conformité",

  // All Menu & Page Names
  "EPCR Registry": "Registre ePCR",
  "QA Forms": "Formulaires AQ",
  "QA Reviews": "Révisions AQ",
  "QA Rules": "Règles AQ",
  "Rules Engine": "Moteur de règles",
  "Form Templates": "Modèles de formulaires",
  "Medication Safety": "Sécurité des médicaments",
  "Bed Management": "Gestion des lits",
  "Patient Scheduling": "Planification des patients",
  "Waitlist Management": "Liste d'attente",
  "TB Case Management": "Gestion de la tuberculose",
  "Home Care Dispatch": "Soins à domicile",
  "My HC Schedule": "Mon horaire de soins",
  "Child & Family Services": "Services à l'enfance",
  "Surgical Care": "Soins chirurgicaux",
  "Ophthalmology": "Ophtalmologie",
  "Dental Care": "Soins dentaires",
  "Long-Term Care": "Soins de longue durée",
  "Mental Health": "Santé mentale",
  "Rehabilitation Services": "Services de réadaptation",
  "Ambulatory Referrals": "Références ambulatoires",
  "Workflows": "Flux de travail",
  "Deployments": "Déploiements",
  "Reports & Analytics": "Rapports et analyses",
  "Feedback Threads": "Commentaires",
  "Medical Travel": "Voyages médicaux",
  "Organizations": "Organisations",
  "User Management": "Gestion des utilisateurs",
  "Support Tickets": "Billets de support",
  "Audit Logs": "Journaux d'audit",
  "System Settings": "Paramètres système",
  "Claims Management": "Gestion des réclamations",
  "Provider Payments": "Paiements prestataires",
  "HIPAA Consent": "Consentement HIPAA",
  "HIPAA Disclosure": "Divulgation HIPAA",
  "Business Associates": "Associés commerciaux",
  "De-Identification Engine": "Moteur de désidentification",
  "Patient Portal": "Portail du patient",
  "Patient History": "Historique patient",
  "Healthcare Registration": "Inscription santé",
  "Break-Glass Emergency": "Accès d'urgence",
  "Critical Follow-Ups": "Suivis critiques",
  "Retention & Archiving": "Rétention et archivage",
  "Ontario Health Integrations": "Intégrations Ontario",
  "User Guide": "Guide de l'utilisateur",

  // ePCR Create & Edit Form Sections
  "Create ePCR Record": "Créer un dossier ePCR",
  "Create New ePCR Record": "Créer un nouveau dossier ePCR",
  "Patient Information": "Informations sur le patient",
  "Incident & Response Details": "Détails de l'incident et de l'intervention",
  "Vitals & Clinical Measurements": "Constantes et mesures cliniques",
  "Treatment & Medications Administered": "Traitements et médicaments administrés",
  "Assessment & Narratives": "Évaluation et récit clinique",
  "Transport & Disposition": "Transport et orientation",
  "Signatures & Sign-Off": "Signatures et validation",
  "Voice-to-ePCR Dictation": "Dictée vocale ePCR",
  "Submit to QA": "Soumettre à l'AQ",
  "Save Draft": "Enregistrer le brouillon",

  // Table Headers & Common Badges
  "Incident #": "Incident nº",
  "Patient Name": "Nom du patient",
  "Date / Time": "Date / Heure",
  "Care Level": "Niveau de soins",
  "Chief Complaint": "Motif de consultation",
  "Assigned To": "Assigné à",
  "Created By": "Créé par",
  "Last Updated": "Dernière mise à jour",
  "Role": "Rôle",
  "Email": "Courriel",
  "Phone": "Téléphone",
  "Address": "Adresse",
  "City": "Ville",
  "Region": "Région",
  "Gender": "Genre",
  "Age": "Âge",
  "DOB": "Date de naissance",
  "Date of Birth": "Date de naissance",
  "Primary Language": "Langue principale",
  "Allergies": "Allergies",
  "Medical History": "Historique médical",
  "Current Medications": "Médicaments actuels",
  "Blood Pressure": "Pression artérielle",
  "Heart Rate": "Fréquence cardiaque",
  "Respiratory Rate": "Fréquence respiratoire",
  "Oxygen Saturation": "Saturation en oxygène (SpO2)",
  "Temperature": "Température",
  "Pain Scale": "Échelle de douleur",
  "Glasgow Coma Scale (GCS)": "Échelle de Glasgow (GCS)",
  "Blood Glucose": "Glycémie"
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('app_lang') || 'en');

  useEffect(() => {
    localStorage.setItem('app_lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const toggleLanguage = () => {
    setLang((prev) => (prev === 'en' ? 'fr' : 'en'));
  };

  const t = (key) => {
    if (!key) return '';
    // 1. Direct translation key match
    if (translations[lang]?.[key]) return translations[lang][key];
    
    // 2. French auto dictionary lookup with exact string
    if (lang === 'fr' && frAutoDictionary[key]) return frAutoDictionary[key];

    // 3. Normalized / trimmed lookup for dynamic placeholders (e.g. "Search patient..." -> "Search patient")
    if (lang === 'fr' && typeof key === 'string') {
      const cleanKey = key.trim().replace(/[.…]+$/, '');
      if (frAutoDictionary[cleanKey]) {
        return key.endsWith('...') || key.endsWith('…') 
          ? `${frAutoDictionary[cleanKey]}...` 
          : frAutoDictionary[cleanKey];
      }
    }

    return key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      lang: 'en',
      setLang: () => {},
      toggleLanguage: () => {},
      t: (key) => key
    };
  }
  return context;
};
