package com.healthcare.epcr.homecare.model;

import com.healthcare.epcr.homecare.enums.VisitStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.time.LocalDate;

/**
 * HomeCareVisit — one individual visit occurrence generated from a HomeCareReferral.
 * Auto-generated by the recurrence engine (HomeCareVisitGenerationJob).
 * A nurse checks in/out from this document in the field via PWA.
 */
@Document(collection = "homeCareVisits")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class HomeCareVisit {

    @Id
    private String id;

    @Indexed
    private String referralId;

    @Indexed
    private String patientId;

    private String patientName;

    @Indexed
    private String organizationId;

    /** Null until dispatcher assigns a nurse. */
    private String assignedNurseId;

    /** Denormalized for fast dispatch board reads. */
    private String assignedNurseName;

    @Indexed
    private String visitDate;

    /**
     * Time window, not exact slot — rural reality.
     * e.g. "09:00-12:00" or "14:00-17:00"
     */
    private String timeWindow;

    /** UNASSIGNED → ASSIGNED → EN_ROUTE → IN_PROGRESS → COMPLETED / MISSED / CANCELLED */
    private VisitStatus status;

    @Indexed
    private String community;

    /** Patient's home coordinates (latitude). */
    private Double latitude;

    /** Patient's home coordinates (longitude). */
    private Double longitude;

    /** When the nurse marked themselves as checked in (started visit). */
    private Instant checkInAt;

    /** When the nurse marked the visit as completed. */
    private Instant checkOutAt;

    /** When nurse was assigned — for audit trail. */
    private Instant assignedAt;

    /** Clinical notes entered by nurse after completion. */
    private String visitNotes;

    /** Clinical instructions from physician. */
    private String careInstructions;

    /** Patient's vital signs observed during visit. */
    private String vitalsRecorded;

    /** Flag for offline-created events — synced from PWA. */
    private Boolean offlineCreated;

    /** Service type inherited from referral for quick filtering. */
    private String serviceType;

    /** Priority inherited from referral. */
    private String priority;

    private Instant createdAt;
    private Instant updatedAt;
}
